language: python

python:
  - "2.6"
  - "2.7"

cache:
  directories:
    - $HOME/.pip-cache/

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "sudo rmdir /dev/shm && sudo ln -Tsf /{run,dev}/shm"

# command to run tests
# script: nosetests
script:
  - 'DEBUG=True python manage.py test $(ls apps | grep -v ".py" | cut -f2 -d"/" )'
  - "DEBUG=True python manage.py harvest features"

before_script:
  - "pep8 --exclude=migrations --show-source --show-pep8 --ignore=E501,E225 carbide apps || echo ''"
#  - "pyflakes -x W app"
