language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "sudo rmdir /dev/shm && sudo ln -Tsf /{run,dev}/shm"

# command to run tests
# script: nosetests
script: 
  - "python manage.py test"
  - "python manage.py harvest features"

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 apps carbide"
#  - "pyflakes -x W app"
