language: python

python:
  - "2.6"
  - "2.7"

cache:
  directories:
    - $HOME/.pip-cache/

# command to install dependencies
install: "pip install -r requirements.txt --download-cache $HOME/.pip-cache"

# command to run tests
# script: nosetests
script: python app/manage.py test

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 app"
#  - "pyflakes -x W app"