#!/usr/bin/env bash

set -e


source env/bin/activate
pep8 --exclude=migrations --ignore=E501,E225 carbide carbide/apps
python manage.py harvest features
python manage.py test $(ls carbide/apps| grep -v ".py" | cut -f2 -d"/" )

